corrected
Anastasija042/Homework1 pull request #2
Opened 2023-06-28 12:32 UTC by Anastasija042

2023-06-28 21:15 UTC, Mielilon requested changes
Основная часть заданий выполнена хорошо. Осталось внести исправления, чтобы работа стала отличной!

2023-06-28 21:15 UTC, Mielilon commented on script.js
> +year = 2007
Переменная не была определена. Нужно воспользоваться ключевым словом `const`, так как данные не предполагают изменения.

2023-06-28 21:15 UTC, Mielilon commented on script.js
> +let creator = "Брендан Эйх";
Аналогично предыдущему комментарию, данные не предполагают изменения, поэтому лучше воспользоваться `const`

2023-06-28 21:15 UTC, Mielilon commented on script.js
> +alert(Сумма: ${a + b});
Нужно взять вывод в алерт в скошенные кавычки. Замечание относится к аналогичным примерам.

2023-06-28 21:15 UTC, Mielilon commented on script.js
> +result = 2 ** 5;
Затерялось определение переменной, нужно добавить.

2023-06-28 21:15 UTC, Mielilon commented on script.js
> +alert("Привет, " + "name" + "!");
`name` – переменная, а не строка. Нужно убрать кавычки.

2023-06-29 13:43 UTC, Anastasija042 commented on script.js
> +alert(Сумма: ${a + b});
я просто не совсем поняла когда их использовать нужно. в аналогичных примерах (сумма, разность, частное, произвед) поставила, так же добавила в заданиях 8 и 10. верно?

2023-06-29 20:13 UTC, Mielilon requested changes
Спасибо за внесенные исправления. Остались замечания, которые требуют доработок.

2023-06-29 20:13 UTC, Mielilon commented on script.js
> +const a = 20;
Требуется вернуть к начальному значению, к данной строке не было комментариев. Сейчас данный код при запуске выдаст ошибку, так как мы пытаемся определить одну и ту же переменную несколько раз.

По условию задачи, на данной строке происходит переопределение, ключевое слово не требуется.

2023-06-29 20:13 UTC, Mielilon commented on script.js
> +year = 2007
Замечание не было исправлено.

2023-06-29 20:13 UTC, Mielilon commented on script.js
> +alert('Сумма: ${a + b}');
Кавычки не были поправлены на скошенные, вывод остается некорректным. Аналогично для кода ниже.

2023-06-29 20:13 UTC, Mielilon commented on script.js
> +alert('"Вам " + age + " лет."');
Либо [интерполяция](https://doka.guide/js/template-strings/), либо [конкатенация](https://doka.guide/js/string/#operacii-so-strokami).

2023-06-29 20:13 UTC, Mielilon commented on script.js
> +alert('"Привет, " + name + "!"');
Аналогично предыдущему комментарию.

2023-06-30 12:33 UTC, Anastasija042 commented on script.js
> +year = 2007
какая-то ошибка, я исправила, мне кажется это неведомый сбой, ниже в первом замечании есть const. Или я неправильно  поняла?

2023-06-30 12:34 UTC, Anastasija042 commented on script.js
> +const a = 20;
вот здесь, задание 2 const присутствует, или не в этом суть? я запуталась((

2023-06-30 12:36 UTC, Anastasija042 commented on script.js
> +alert('Сумма: ${a + b}');
тут да, я перепутала кавычки(( блин. но решение задания 2 у меня не так выглядит(

2023-07-01 17:48 UTC, merged